### ISSUE TITLE
JAR file does not contain latest Scroll&Swipe update

### ISSUE THREAD

**Issue by corneln-roweb** [detroit-labs/katalon-mobile-util#14]
Hi Cris,

Thank you for this **BRILLIANT** library, it is pure gold!
Can you please help producing a new JAR file that includes your latest Swipe&Scroll updates (2 days ago, for Katalon 6.2.0/Appium 1.12.1)?
You can see what I mean bellow:
![image](https://user-images.githubusercontent.com/42569288/59840250-a53ba500-935a-11e9-8bb0-81325184847a.png)

Thank you,
Cornel

**Comment by ctrevarthen** [comment]
Hi @corneln-roweb thanks for the kind words.

I just pushed up the 1.12.0 release, which has support for the official Katalon Studio 6.2.0 release.

Please let me know if you have any issues!
